// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dominio.Tipos
{
    public enum Fuentes : short
    {
        Desconocido = 0,
        Sri = 1,
        Balance = 2,
        Balances = 3,
        Iess = 4,
        Afiliado = 5,
        Contactos = 6,
        ContactosEmpresa = 7,
        Ciudadano = 8,
        Senescyt = 9,
        FJudicial = 10,
        FJEmpresa = 11,
        Ant = 12,
        Proveedor = 13,
        ProveedorContraloria = 14,
        EmpresasSimilares = 15,
        Familiares = 16,
        Personales = 17,
        DirectorioCompanias = 18,
        AnalisisHorizontal = 19,
        BuroCredito = 20,
        RepresentantesEmpresas = 21,
        FiscaliaDelitosPersona = 22,
        FiscaliaDelitosEmpresa = 23,
        PensionAlimenticia = 24,
        CatastroFantasma = 25,
        SuperBancos = 26,
        AntecedentesPenales = 27,
        PredioMunicipio = 28,
        PredioMunicipioEmpresa = 29,
        RegistroCivil = 30,
        SuperBancosNatural = 31,
        SuperBancosEmpresa = 32,
        DetallePredios = 33,
        DetallePrediosEmpresa = 34,
        PredioMunicipioCuenca = 35,
        PredioMunicipioEmpresaCuenca = 36,
        AfiliadoAdicional = 37,
        PredioMunicipioSantoDomingo = 38,
        PredioMunicipioEmpresaSantoDomingo = 39,
        PredioMunicipioRuminahui = 40,
        PredioMunicipioEmpresaRuminahui = 41,
        PredioMunicipioQuininde = 42,
        PredioMunicipioEmpresaQuininde = 43,
        IessEmpresaEmpleados = 44,
        UafeOnu = 45,
        UafeOnu2206 = 46,
        UafeInterpol = 47,
        UafeOfac = 48,
        ContactosIess = 49,
        Accionistas = 50,
        EmpresasAccionista = 51,
        AutoHistorico = 52,
        Impedimento = 53,
        PredioMunicipioLatacunga = 54,
        PredioMunicipioEmpresaLatacunga = 55,
        RentasSri = 56,
        PredioMunicipioManta = 57,
        PredioMunicipioEmpresaManta = 58,
        PredioMunicipioAmbato = 59,
        PredioMunicipioEmpresaAmbato = 60,
        PredioMunicipioIbarra = 61,
        PredioMunicipioEmpresaIbarra = 62,
        PredioMunicipioSanCristobal = 63,
        PredioMunicipioEmpresaSanCristobal = 64,
        PredioMunicipioDuran = 65,
        PredioMunicipioEmpresaDuran = 66,
        PredioMunicipioLagoAgrio = 67,
        PredioMunicipioEmpresaLagoAgrio = 68,
        PredioMunicipioSantaRosa = 69,
        PredioMunicipioEmpresaSantaRosa = 70,
        PredioMunicipioSucua = 71,
        PredioMunicipioEmpresaSucua = 72,
        PredioMunicipioSigSig = 73,
        PredioMunicipioEmpresaSigSig = 74,
        FuerzaArmada = 75,
        DeNoBaja = 76,
        PredioMunicipioMejia = 77,
        PredioMunicipioEmpresaMejia = 78,
        PredioMunicipioMorona = 79,
        PredioMunicipioEmpresaMorona = 80,
        PredioMunicipioTena = 81,
        PredioMunicipioEmpresaTena = 82,
        PredioMunicipioCatamayo = 83,
        PredioMunicipioEmpresaCatamayo = 84,
        PredioMunicipioLoja = 85,
        PredioMunicipioEmpresaLoja = 86,
        DetallePrediosLoja = 87,
        DetallePrediosEmpresaLoja = 88,
        PredioMunicipioSamborondon = 89,
        PredioMunicipioEmpresaSamborondon = 90,
        PredioMunicipioDaule = 91,
        PredioMunicipioEmpresaDaule = 92,
        PredioMunicipioCayambe = 93,
        PredioMunicipioEmpresaCayambe = 94,
        PredioMunicipioAzogues = 95,
        PredioMunicipioEmpresaAzogues = 96,
        PredioMunicipioEsmeraldas = 97,
        PredioMunicipioEmpresaEsmeraldas = 98,
        PredioMunicipioCotacachi = 99,
        PredioMunicipioEmpresaCotacachi = 100,
        VerificarAccionistas = 101,
        IessJubilado = 102,

        #region FuentesEquifax
        NivelTotalDeudaHistorica = 2021,
        NivelEvolucionHistoricaDistribucionEndeudamiento = 2022,
        NivelHistoricoEstructuraVencimientos = 2023,
        NivelOperacionesPorInstitucion = 2024,
        NivelSaldoPorVencerPorInstitucion = 2025,
        NivelDetalleVencidoPorInstitucion = 2026,
        NivelDetalleOperacionesYEntidades = 2027,
        NivelOperacionesPorInstitucionPV = 2028,
        #endregion FuentesEquifax

        //Clientes Custom
        BalancesAmc = 201

    }
}
