// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dominio.Tipos
{
    public enum Politicas : short
    {
        Desconocido = 0,

        AntiguedadRucNatural = 1,
        ImpuestoRentaNatural = 2,
        ISDNatural = 3,
        DeudaFirmeNatural = 4,
        Civil = 5,
        IessMoraPatronal = 6,
        IessAfiliacion = 7,
        NivelEstudios = 8,
        LegalPersona = 9,
        LegalDemandante = 10,
        Sercop = 11,

        AntiguedadRucCedula = 12,
        ImpuestoRentaCedula = 13,
        ISDCedula = 14,
        DeudaFirmeCedula = 15,
        CivilCedula = 16,
        IessMoraPatronalCedula = 17,
        IessAfiliacionCedula = 18,
        NivelEstudiosCedula = 19,
        LegalPersonaCedula = 20,
        LegalDemandanteCedula = 21,
        SercopCedula = 22,

        AntiguedadRucJuridico = 23,
        ImpuestoRentaJuridico = 24,
        ISDJuridico = 25,
        DeudaFirmeJuridico = 26,
        CivilJuridico = 27,

        SocietarioAnioConstitucionJuridico = 28,
        SocietarioCapitalSuscritoJuridico = 29,
        SocietarioEstadoJuridico = 30,
        SocietarioIndicesLiquidezCorrienteJuridico = 31,
        SocietarioIndicesPeriodoMedioCobranzaJuridico = 32,
        SocietarioBalancesTotalActivosJuridico = 33,
        SocietarioBalancesTotalPasivosJuridico = 34,
        SocietarioBalancesPatrimonioNetoJuridico = 35,

        SocietarioIngresosyGastosEfectivoCajaJuridico = 36,
        SocietarioIngresosyGastosTotalIngresosJuridico = 37,
        SocietarioIngresosyGastosGastosOperacionalesJuridico = 38,
        SocietarioIngresosyGastos15TrabajadoresJuridico = 39,
        SocietarioIngresosyCuentasxPagarProveedoresTercerosJuridico = 40,
        SocietarioIngresosyUtilidadEjercicioJuridico = 41,

        IessMoraPatronalJuridico = 42,
        IessAfiliacionJuridico = 43,
        NivelEstudiosJuridico = 44,
        LegalPersonaJuridico = 45,
        LegalPersonaJuridicoEmpresa = 46,
        LegalDemandanteJuridico = 47,
        LegalDemandanteJuridicoEmpresa = 48,
        SercopJuridico = 49,

        ContactarmeDireccionesCedula = 50,
        ContactarmeTelefonosCedula = 51,
        ContactarmeEmailsCedula = 52,

        ContactarmeDireccionesNatural = 53,
        ContactarmeTelefonosNatural = 54,
        ContactarmeEmailsNatural = 55,

        ContactarmeDireccionesJuridico = 56,
        ContactarmeTelefonosJuridico = 57,
        ContactarmeEmailsJuridico = 58,

        ManejodeCuentasCorrientesNatural = 59,
        DeudaVigenteTotalNatural = 60,
        ValorDemandaJudicialNatural = 61,
        ValorCarteraCastigadaNatural = 62,
        ValorCuotaVencidosNatural = 63,
        SaldoVencidoTarjetasNatural = 64,
        ValorDemandaJudicialTarjetasNatural = 65,
        CarteraCastigadaTarjetasNatural = 66,
        DiasMorosidadTarjetasNatural = 67,
        ValorVencidoTotalBancosNatural = 68,
        ValorDemandaJudicialBancosNatural = 69,
        ValorCarteraCastigadaBancosNatural = 70,
        DiasMorosidadBancosNatural = 71,
        ValorVencidoTotalCooperativasNatural = 72,
        ValorDemandaJudicialCooperativasNatural = 73,
        ValorCarteraCastigadaCooperativasNatural = 74,
        DiasMorosidadCooperativasNatural = 75,
        ValorVencidoTotalEmpresasNatural = 76,
        ValorDemandaJudicialEmpresasNatural = 77,
        ValorCarteraCastigadaEmpresasNatural = 78,
        DiasMorosidadEmpresasNatural = 79,
        ValorVencidoVigentesServiciosNatural = 80,
        NumeroDiasVencidoVigentesServiciosNatural = 81,
        ValorVencidoVigentesCobranzasNatural = 82,
        DemandaJudicialVigentesCobranzasNatural = 83,
        CarteraCastigadaVigentesCobranzasNatural = 84,
        NumeroDiasVencidoVigentesCobranzasNatural = 85,
        MayorSaldoVencido36MesesNatural = 86,
        ValorVencidoHistoricoTarjetasNatural = 87,
        ValorVencidoHistoricoBancosNatural = 88,
        ValorVencidoHistoricoCooperativasNatural = 89,
        ValorVencidoHistoricoEmpresasNatural = 90,
        ValorVencidoHistoricoServicioNatural = 91,
        ValorVencidoHistoricoCobranzaNatural = 92,
        ManejodeCuentasCorrientesCedula = 93,
        DeudaVigenteTotalCedula = 94,
        ValorDemandaJudicialCedula = 95,
        ValorCarteraCastigadaCedula = 96,
        ValorCuotaVencidosCedula = 97,
        SaldoVencidoTarjetasCedula = 98,
        ValorDemandaJudicialTarjetasCedula = 99,
        CarteraCastigadaTarjetasCedula = 100,
        DiasMorosidadTarjetasCedula = 101,
        ValorVencidoTotalBancosCedula = 102,
        ValorDemandaJudicialBancosCedula = 103,
        ValorCarteraCastigadaBancosCedula = 104,
        DiasMorosidadBancosCedula = 105,
        ValorVencidoTotalCooperativasCedula = 106,
        ValorDemandaJudicialCooperativasCedula = 107,
        ValorCarteraCastigadaCooperativasCedula = 108,
        DiasMorosidadCooperativasCedula = 109,
        ValorVencidoTotalEmpresasCedula = 110,
        ValorDemandaJudicialEmpresasCedula = 111,
        ValorCarteraCastigadaEmpresasCedula = 112,
        DiasMorosidadEmpresasCedula = 113,
        ValorVencidoVigentesServiciosCedula = 114,
        NumeroDiasVencidoVigentesServiciosCedula = 115,
        ValorVencidoVigentesCobranzasCedula = 116,
        DemandaJudicialVigentesCobranzasCedula = 117,
        CarteraCastigadaVigentesCobranzasCedula = 118,
        NumeroDiasVencidoVigentesCobranzasCedula = 119,
        MayorSaldoVencido36MesesCedula = 120,
        ValorVencidoHistoricoTarjetasCedula = 121,
        ValorVencidoHistoricoBancosCedula = 122,
        ValorVencidoHistoricoCooperativasCedula = 123,
        ValorVencidoHistoricoEmpresasCedula = 124,
        ValorVencidoHistoricoServicioCedula = 125,
        ValorVencidoHistoricoCobranzaCedula = 126,
        ManejodeCuentasCorrientesJuridico = 127,
        DeudaVigenteTotalJuridico = 128,
        ValorDemandaJudicialJuridico = 129,
        ValorCarteraCastigadaJuridico = 130,
        ValorCuotaVencidosJuridico = 131,
        SaldoVencidoTarjetasJuridico = 132,
        ValorDemandaJudicialTarjetasJuridico = 133,
        CarteraCastigadaTarjetasJuridico = 134,
        DiasMorosidadTarjetasJuridico = 135,
        ValorVencidoTotalBancosJuridico = 136,
        ValorDemandaJudicialBancosJuridico = 137,
        ValorCarteraCastigadaBancosJuridico = 138,
        DiasMorosidadBancosJuridico = 139,
        ValorVencidoTotalCooperativasJuridico = 140,
        ValorDemandaJudicialCooperativasJuridico = 141,
        ValorCarteraCastigadaCooperativasJuridico = 142,
        DiasMorosidadCooperativasJuridico = 143,
        ValorVencidoTotalEmpresasJuridico = 144,
        ValorDemandaJudicialEmpresasJuridico = 145,
        ValorCarteraCastigadaEmpresasJuridico = 146,
        DiasMorosidadEmpresasJuridico = 147,
        ValorVencidoVigentesServiciosJuridico = 148,
        NumeroDiasVencidoVigentesServiciosJuridico = 149,
        ValorVencidoVigentesCobranzasJuridico = 150,
        DemandaJudicialVigentesCobranzasJuridico = 151,
        CarteraCastigadaVigentesCobranzasJuridico = 152,
        NumeroDiasVencidoVigentesCobranzasJuridico = 153,
        MayorSaldoVencido36MesesJuridico = 154,
        ValorVencidoHistoricoTarjetasJuridico = 155,
        ValorVencidoHistoricoBancosJuridico = 156,
        ValorVencidoHistoricoCooperativasJuridico = 157,
        ValorVencidoHistoricoEmpresasJuridico = 158,
        ValorVencidoHistoricoServicioJuridico = 159,
        ValorVencidoHistoricoCobranzaJuridico = 160,

        GastosFinancierosCedula = 161,
        GastosFinancierosNatural = 162,

        FechaCumplimientoSancionCedula = 163,
        FechaCumplimientoSancionNatural = 164,
        FechaCumplimientoSancionJuridico = 165,

        EstadoTributarioCedula = 166,
        EstadoTributarioNatural = 167,
        EstadoTributarioJuridico = 168,

        PermisoFacturacionCedula = 169,
        PermisoFacturacionNatural = 170,
        PermisoFacturacionJuridico = 171,

        PagoPendientePensionAlimenticiaCedula = 172,
        PagoPendientePensionAlimenticiaNatural = 173,
        PagoPendientePensionAlimenticiaJuridico = 174,

        ValorVencido12MesesJuridico = 175,
        ValorDemandaJudicial12MesesJuridico = 176,
        CarteraCastigada12MesesJuridico = 177,

        ValorVencido12MesesNatural = 178,
        ValorDemandaJudicial12MesesNatural = 179,
        CarteraCastigada12MesesNatural = 180,

        ValorVencido12MesesCedula = 181,
        ValorDemandaJudicial12MesesCedula = 182,
        CarteraCastigada12MesesCedula = 183,

        ValorVencidoMayor12MesesJuridico = 184,
        ValorDemandaJudicialMayor12MesesJuridico = 185,
        CarteraCastigadaMayor12MesesJuridico = 186,

        ValorVencidoMayor12MesesNatural = 187,
        ValorDemandaJudicialMayor12MesesNatural = 188,
        CarteraCastigadaMayor12MesesNatural = 189,

        ValorVencidoMayor12MesesCedula = 190,
        ValorDemandaJudicialMayor12MesesCedula = 191,
        CarteraCastigadaMayor12MesesCedula = 192,

        PagoMultasPendienteCedula = 193,
        PagoMultasPendienteNatural = 194,
        PagoMultasPendienteJuridico = 195,

        SuperintendenciaBancosCedula = 196,
        SuperintendenciaBancosNatural = 197,
        SuperintendenciaBancosJuridico = 198,

        PrediosPersonalCedula = 199,
        PrediosPersonalNatural = 200,
        PrediosPersonalRepLegal = 201,
        PrediosEmpresariales = 202,

        AntecedentesPenalesCedula = 203,
        AntecedentesPenalesNatural = 204,
        AntecedentesPenalesJuridico = 205,

        NoticiasDelitoCedula = 206,
        NoticiasDelitoNatural = 207,
        NoticiasDelitoJuridico = 208,
        NoticiasDelitoEmpresaJuridico = 209,

        SuperintendenciaBancosRNCedula = 210,
        SuperintendenciaBancosCNatural = 211,
        SuperintendenciaBancosCJuridico = 212,
        SuperintendenciaBancosRNJuridico = 213,
        SocietarioUltimoAnioBalance = 214,
        TituloNivelSuperiorCedula = 215,
        TituloNivelSuperiorNatural = 216,
        TituloNivelSuperiorJuridico = 217,

        #region Cliente_1790325083001

        quiceTrabajadoresMicrocredito = 10000,
        antecedentesPenalesMicrocredito = 10001,
        antecedentesPenalesConsumo = 10002,
        antiguedadRucMicrocredito = 10003,
        antiguedadRucConsumo = 10004,
        anioConstitucionMicrocredito = 10005,
        capitalSuscritoMicrocredito = 10006,
        contactableDireccionesMicrocredito = 10007,
        contactableDireccionesConsumo = 10008,
        contactableEmailsMicrocredito = 10009,
        contactableEmailsConsumo = 10010,
        contactableTelefonosMicrocredito = 10011,
        contactableTelefonosConsumo = 10012,
        cuentasPagarProveedoresTercerosMicrocredito = 10013,
        deudaFirmeMicrocredito = 10014,
        deudaFirmeConsumo = 10015,
        edadMicrocredito = 10016,
        edadConsumo = 10017,
        efectivoCajaMicrocredito = 10018,
        estadoJuridicoMicrocredito = 10019,
        estadoTributarioMicrocredito = 10020,
        gastosOperacionalesMicrocredito = 10021,
        iessAfiliacionMicrocredito = 10022,
        iessMoraPatronalMicrocredito = 10023,
        iessMoraPatronalConsumo = 10024,
        impuestoRentaMicrocredito = 10025,
        impuestoRentaConsumo = 10026,
        liquidezCorrienteMicrocredito = 10027,
        noticiasDelitoMicrocredito = 10028,
        noticiasDelitoEmpresaMicrocredito = 10029,
        noticiasDelitoConsumo = 10030,
        pagoMultasPendientesMicrocredito = 10031,
        pagoMultasPendientesConsumo = 10032,
        pagoPendientePensionAlimenticiaMicrocredito = 10033,
        pagoPendientePensionAlimenticiaConsumo = 10034,
        patrimonioNetoMicrocredito = 10035,
        periodoMedioCobranzaMicrocredito = 10036,
        permisoFacturacionMicrocredito = 10037,
        permisoFacturacionConsumo = 10038,
        sercopMicrocredito = 10039,
        sercopConsumo = 10040,
        superintendenciaBancosCedulaMicrocredito = 10041,
        superintendenciaBancosCedulaConsumo = 10042,
        superintendenciaBancosEmpresaMicrocredito = 10043,
        superintendenciaBancosRucNaturalMicrocredito = 10044,
        superintendenciaBancosRucNaturalConsumo = 10045,
        titulosSenescytMicrocredito = 10046,
        titulosSenescytConsumo = 10047,
        totalActivosMicrocredito = 10048,
        totalIngresosMicrocredito = 10049,
        totalPasivosMicrocredito = 10050,
        ultimoAnioBalanceMicrocredito = 10051,
        utilidadEjercicioMicrocredito = 10052,
        vehiculosMicrocredito = 10053,
        vehiculosConsumo = 10054,
        propiedadesMicrocredito = 10055,
        propiedadesConsumo = 10056,

        #endregion Cliente_1790325083001

        #region Cliente_0990304211001
        NacionalidadCedula = 20001,
        NacionalidadNatural = 20002,
        NacionalidadJuridico = 20003,
        ProfesionCedula = 20004,
        ProfesionNatural = 20005,
        ProfesionJuridico = 20006,
        ListaObservadosCedula = 20007,
        ListaObservadosNatural = 20008,
        ListaObservadosJuridico = 20009,
        #endregion Cliente_0990304211001

        #region Cliente_1091796789001
        NacionalidadCedulaRagui = 30001,
        NacionalidadNaturalRagui = 30002,
        NacionalidadJuridicoRagui = 30003,
        PagoRentasCedulaRagui = 30004,
        PagoRentasNaturalRagui = 30005,
        PagoRentasJuridicoRagui = 30006,
        PresentarDeudasCedulaRagui = 30007,
        PresentarDeudasNaturalRagui = 30008,
        PresentarDeudasJuridicoRagui = 30009,
        DependenciaLaboralCedulaRagui = 30010,
        DependenciaLaboralNaturalRagui = 30011,
        DependenciaLaboralJuridicoRagui = 30012,
        IngresoMinimoCedulaRagui = 30013,
        IngresoMinimoNaturalRagui = 30014,
        IngresoMinimoJuridicoRagui = 30015,
        CiudadanoExtranjeroCedulaRagui = 30016,
        CiudadanoExtranjeroNaturalRagui = 30017,
        CiudadanoExtranjeroJuridicoRagui = 30018,
        ScoreCedulaRagui = 30019,
        ScoreNaturalRagui = 30020,
        ScoreJuridicoRagui = 30021,
        #endregion Cliente_1091796789001

        #region Cliente_0990981930001
        NacionalidadCedulaLitoral = 30101,
        NacionalidadNaturalLitoral = 30102,
        NacionalidadJuridicoLitoral = 30103,
        CuentasInhabilitadasCedulaLitoral = 9001,
        CuentasInhabilitadasNaturalLitoral = 9002,
        CuentasInhabilitadasJuridicoLitoral = 9003,
        EstabilidadDependienteCedulaLitoral = 3001,
        EstabilidadDependienteNaturalLitoral = 3002,
        EstabilidadDependienteJuridicoLitoral = 3003
        #endregion Cliente_0990981930001
    }
}
